
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 29 19:29:06 BRT 2025
//----------------------------------------------------

package provaQ2;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ATRIBUICAO = 8;
  public static final int INTEIRO = 9;
  public static final int PROGRAMA = 2;
  public static final int OP_ARITMETICO = 16;
  public static final int TIPO_INTEIRO = 5;
  public static final int INICIO = 3;
  public static final int PTVG = 7;
  public static final int EOF = 0;
  public static final int FIM = 4;
  public static final int IF = 12;
  public static final int TIPO_FLOAT = 6;
  public static final int CONDICIONAL = 15;
  public static final int error = 1;
  public static final int FECHA_PARENTESES = 14;
  public static final int VARIAVEL = 11;
  public static final int ABRE_PARENTESES = 13;
  public static final int FLOAT = 10;
}

