
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 29 21:41:51 BRT 2025
//----------------------------------------------------

package provaQ3;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int MULT = 3;
  public static final int error = 1;
  public static final int ADD = 4;
  public static final int DIV = 5;
  public static final int PTVG = 2;
  public static final int EOF = 0;
}

